@startuml
'https://plantuml.com/sequence-diagram

participant 前端页面 as front
participant 多轮AI智能对话系统 as backend
participant Redis as redis
participant DeepSeek大模型 as deepseek

alt ===>>> 多轮AI智能对话系统流程 <<<===
activate front
front -> backend : 前端调用后端接口发送数据
activate backend
backend -> backend : 解析参数，创建用户消息上下文对象
backend -> redis :  查询历史对话上下文
activate redis
redis --> backend : 返回历史会话上下文
deactivate redis
backend -> backend : 历史会话上下文添加到用户消息上下文对象
backend -> deepseek : 传递用户消息上下文对象，调用DeepSeek大模型接口
activate deepseek
deepseek -> deepseek : 根据接收的参数智能化生成响应结果数据
deepseek --> backend : 返回大模型响应的数据
deactivate deepseek
backend -> redis : 添加AI回复的上下文
activate redis
redis --> backend : 返回添加结果
deactivate redis
backend --> front : 返回大模型响应的数据
deactivate backend

front -> backend : 健康检查
activate backend
backend --> front: 响应结果数据
deactivate backend
deactivate front
end
@enduml